threadpool: pool.cpp  example.cpp task.h threadpool.h
		c++ -std=c++11  ../server/ss.cpp pool.cpp  example.cpp -o threadpool 
nothreadpool: example2.cpp 
		c++ -std=c++11  ../server/ss.cpp example2.cpp -o nothreadpool 